# Generated by Django 6.0.5 on 2026-05-27 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_is_featured_course_is_featured_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admission_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admission_fee_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admission_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admission_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('admitted', 'Admitted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_students', to='courses.course'),
        ),
        migrations.CreateModel(
            name='AdmissionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=20000, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('payment_reference', models.CharField(max_length=200, unique=True)),
                ('flutterwave_tx_id', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
