# Generated by Django 6.0.5 on 2026-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage featured section'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage featured section'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage featured section'),
        ),
    ]
