# Generated by Django 6.0.5 on 2026-05-26 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterwaveTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_ref', models.CharField(help_text='Our transaction reference', max_length=200, unique=True)),
                ('flw_ref', models.CharField(blank=True, help_text='Flutterwave reference', max_length=200)),
                ('transaction_id', models.CharField(blank=True, help_text='Flutterwave transaction ID', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('payment_type', models.CharField(blank=True, help_text='e.g. mobilemoneyuganda, card', max_length=50)),
                ('raw_payload', models.JSONField(default=dict, help_text='Full webhook payload for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flutterwave Transaction',
                'verbose_name_plural': 'Flutterwave Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway', models.CharField(default='flutterwave', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Payment',
                'verbose_name_plural': 'Course Payments',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
