# Generated by Django 6.0.5 on 2026-05-28 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('zoom_sessions', '0002_alter_zoomsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('payment_reference', models.CharField(max_length=200, unique=True)),
                ('flutterwave_tx_id', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='zoom_sessions.zoomsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='FlutterwaveTransaction',
        ),
        migrations.AlterModelOptions(
            name='coursepayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='coursepayment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='flutterwave_tx_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coursepayment',
            name='payment_reference',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='coursepayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='coursepayment',
            name='gateway',
        ),
    ]
