# Generated by Django 6.0.5 on 2026-05-26 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('zoom_link', models.URLField(help_text='Zoom meeting URL — only revealed after payment')),
                ('meeting_id', models.CharField(blank=True, help_text='Zoom Meeting ID', max_length=50)),
                ('passcode', models.CharField(blank=True, help_text='Zoom Meeting Passcode', max_length=50)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('max_participants', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='session_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'role__in': ['instructor', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoom_sessions_hosted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zoom Session',
                'verbose_name_plural': 'Zoom Sessions',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoomPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction reference from payment gateway', max_length=200)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway', models.CharField(default='flutterwave', help_text='Payment gateway used', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_payments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='zoom_sessions.zoomsession')),
            ],
            options={
                'verbose_name': 'Zoom Payment',
                'verbose_name_plural': 'Zoom Payments',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
