# Generated by Django 6.0.5 on 2026-05-28 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoomsession',
            options={'ordering': ['-scheduled_at']},
        ),
        migrations.RemoveField(
            model_name='zoomsession',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='zoomsession',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='zoomsession',
            name='meeting_id',
        ),
        migrations.RemoveField(
            model_name='zoomsession',
            name='passcode',
        ),
        migrations.RemoveField(
            model_name='zoomsession',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='zoomsession',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='zoomsession',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoom_sessions_hosting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zoomsession',
            name='zoom_link',
            field=models.URLField(help_text='Only revealed after successful payment'),
        ),
        migrations.CreateModel(
            name='ZoomRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='zoom_sessions.zoomsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.DeleteModel(
            name='ZoomPayment',
        ),
    ]
